device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'gtsrb'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 10
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR


model: 'preactresnet18'
random_seed: 0
index: 
alpha: 1/255
eps: 4/255
steps: 4
ratio: 0.05


